### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by ds2268** [zlinker/DehazeNet#2]
Hi,

I saw that the architecture seems to be different compared to the original DehazeNet. There seems to be no BRelu units, the stadard Relu units are used instead. Also the architecture alone seems to be a little bit different. For example in the feature extraction phase there is supossed to be maxout unit only. You performed maxout using max pooling after Relu activation etc. Also the filter numbers are a bit different. What are the reasons ?

**Comment by zlinker** [comment]
it can be seen as a lite version and it also works, though using brelu and maxout is better :)
